In [ ]:
from nucleo.io.reading import finding_one_parquet
import polars as pl
import numpy as np
import matplotlib.pyplot as plt

root = "/home/nicolas/Documents/Workspace/nucleo/outputs/NUCLEO__PSMN__2026-06-19"

params_fixed = {
    "algo": "1S", 
    "fact": False, 
    "mode": "none", 
    "dstr": False,
    "s": 150,
    "mu": 160, 
    "theta": 20, 
    "alphar": 0.00, 
    "Kp": 0.00, 
    "Kz": 0.00
}

root_config = "/home/nicolas/Documents/Workspace/nucleo/outputs/NUCLEO__PSMN__2026-06-19/scenarios.json"
df_config = pl.read_json(root_config)
# print(df_config)

fig, axes = plt.subplots(ncols=1, nrows=df_config.height, figsize=(8, 4*df_config.height))
for (ax, row) in zip(axes, df_config.iter_rows()):

    land = row[3]
    l = row[1]
    bpmin = row[2]

    params_row = {
        **params_fixed,
        "land": land,
        "l": l,
        "bpmin": bpmin
    }

    df_plot = finding_one_parquet(
        root=root,
        params=params_row
    )

    tbj_points = df_plot["tbj_points"][0].to_numpy()
    tbj_distrib = df_plot["tbj_distrib"][0].to_numpy()
    
    title_dict = {
        "s": params_fixed["s"],
        "l": l,
        "bpmin": bpmin,
        "land": land
    }

    title = str(title_dict)
    ax.set_title(title)
    ax.plot(tbj_points, tbj_distrib)
    ax.set_xlabel("Waiting Time")
    ax.set_ylabel("Distribution")
    ax.grid(True, which="both", alpha=0.30)

plt.tight_layout()
plt.show()
# fig.savefig("/tmp/fig3.png", dpi=150, bbox_inches="tight")

Scanning 222200 parquet files...
[0.0000e+00 1.0000e+00 2.0000e+00 ... 9.9997e+04 9.9998e+04 9.9999e+04] [0.02389945 0.02372241 0.02330934 ... 0.         0.         0.        ]
Scanning 222200 parquet files...
[0.0000e+00 1.0000e+00 2.0000e+00 ... 9.9997e+04 9.9998e+04 9.9999e+04] [0.04411895 0.0445273  0.04191744 ... 0.         0.         0.        ]
Scanning 222200 parquet files...
[0.0000e+00 1.0000e+00 2.0000e+00 ... 9.9997e+04 9.9998e+04 9.9999e+04] [0.06562133 0.05974133 0.05714949 ... 0.         0.         0.        ]
Scanning 222200 parquet files...
[0.0000e+00 1.0000e+00 2.0000e+00 ... 9.9997e+04 9.9998e+04 9.9999e+04] [0.08463886 0.07788245 0.06995234 ... 0.         0.         0.        ]
Scanning 222200 parquet files...
[0.0000e+00 1.0000e+00 2.0000e+00 ... 9.9997e+04 9.9998e+04 9.9999e+04] [0.10098592 0.08947066 0.08270051 ... 0.         0.         0.        ]
Scanning 222200 parquet files...
[0.0000e+00 1.0000e+00 2.0000e+00 ... 9.9997e+04 9.9998e+04 9.9999e+04] [0.1750057